[package]
name = "iron-silk"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.15.0", features = ["tch"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
uuid = { version = "1.11.1", features = ["v4", "fast-rng", "serde"] }
